import Config

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Optional: better HEEx annotations in development (LiveView 1.1)
config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true

# Configure your database
config :prices, Prices.Repo,
  username: "postgres",
  password: "",
  hostname: "localhost",
  database: "prices_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  log: false

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :prices, PricesWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "eIAoB+kuit0gfaxLCh2VRvWGFgoU97gGGZ4j+JvnHyCN4mVWj+2ghYo8jkWRX1/S",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:prices, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:prices, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :prices, PricesWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/prices_web/(live|views)/.*(ex)$",
      ~r"lib/prices_web/templates/.*(eex|heex)$",
      ~r"lib/prices_web/components/.*(ex)$"
    ]
  ]
